@isTest
class TeaTest {
    @isTest
    static void TeaTest1() {
        // Tea tea = new Tea();
        // Set<String> orderTea = tea.orderTea();
        // System.debug(orderTea);
        Set<String> tea = Tea.orderTea();
        // Set<String> testTypes = new Set <String>();
        // testTypes.add('Black');
        // testTypes.add('White');
        // testTypes.add('Herbal');
        // System.assertEqual(orderTea, testTypes, 'エラーです');
    }
}